# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d56d9d5a454a811f113968ef3375fd782484e0514376ea1cc354dc4f9119410bf08549ca41540f85b40ce5a1c1667e4bb2656767176f2f4ae025ab9469311ce

test:
  secret_key_base: 12d0117a0c6360045c1f489f00a931e380d444aa70d46098aaf85f638a38b4ca37aa16310705c6d92f7c6871bf62a52e76ce6048c1554af6df572023166dd6f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
