# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfce990756f875c331a1930265d31668dc13f786e0092c211328cf11d00d34c90582efa8bbab20b37f728984dcc3bf1b54196efe55036615c69b08cd43ce327e

test:
  secret_key_base: 4a3e2a45bacc7d1ba4a5e820639c317e3aebec063d59b890c18d16df7a509a84354251da23b8144378f51c0b94df6894af8959f4e83efef41b2c58de4900c0c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
