# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c445861922036cde0e952cdde566cb5f49c5f866afef2ce8541fc8fc06ce521a5643e7f81e1b75039bc71090d7c72d58b64256be2ee6f52b92315823fc1886fd

test:
  secret_key_base: 7ba0a3c225df1568feb9ae1a135a2c0689023de3c2b0615473282f3888cb79c75c03a82244a1d920b7bb130fd175c8dc641b17bc3ae2d82ee0bafb6f17c2e9d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
